---
- hosts: blog.mpr0xy.com
  remote_user: root
  
  tasks:
  - name: add user mpr0xy
    user: name=mpr0xy groups=sudo,adm,ssh password=your password hash
  - name: copy id_rsa to blog.mpr0xy.com
    copy: src=/home/mcpr0xy/.ssh/id_rsa.pub dest=/home/mpr0xy/.ssh/
  - name: make authorized_keys
    shell: cat /home/mpr0xy/.ssh/id_rsa.pub > /home/mpr0xy/.ssh/authorized_keys
  - name: add sudo_user_list
    shell: echo "mpr0xy ALL=(ALL) ALL" >> /etc/sudoers.d/sudo_user_list  

